# Generated by Django 4.2.13 on 2024-06-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('departure_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('date_of_journey', models.DateField()),
                ('time_of_departure', models.TimeField()),
                ('number_of_seats', models.IntegerField()),
                ('seat_preference', models.CharField(choices=[('window', 'Window'), ('aisle', 'Aisle'), ('any', 'Any')], max_length=10)),
            ],
        ),
    ]
